[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "interest-cohort=()"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "dist/img", # Images processed with eleventy-img plugin
      ".cache",    # Remote Asset Cache
    ]
