# Run percy snapshots
name: Run Percy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Percy
        run: npx @percy/cli snapshot snapshots.prod.yml
